name = "pikto"
compatibility_date = "2025-12-01"
main = "./worker.ts"

routes = [
	{ pattern = "alexeycorr.dev/pikto*", zone_name = "alexeycorr.dev" },
	{ pattern = "alexeycorr.dev/ru/pikto*", zone_name = "alexeycorr.dev" },
	{ pattern = "alexeycorr.dev/en/pikto*", zone_name = "alexeycorr.dev" }
]

[assets]
binding = "ASSETS"
directory = "./dist"
